# Generated by Django 4.1.7 on 2023-03-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wydarzenia", "0004_message_cena_message_data_room_cena_room_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="price",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="message",
            name="body",
        ),
        migrations.RemoveField(
            model_name="message",
            name="data",
        ),
        migrations.AddField(
            model_name="message",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
