# Generated by Django 4.1.6 on 2023-03-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wydarzenia", "0006_room_location_alter_room_name_alter_topic_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
    ]
