# Generated by Django 4.1.7 on 2023-03-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wydarzenia", "0006_alter_room_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
