# Generated by Django 4.1.7 on 2023-03-21 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wydarzenia", "0006_alter_room_description"),
        ("wydarzenia", "0007_alter_room_description"),
    ]

    operations = []
