# Generated by Django 4.1.6 on 2023-03-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wydarzenia", "0007_topic_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
