# Generated by Django 4.1.7 on 2023-03-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wydarzenia", "0009_alter_room_description_alter_room_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.RemoveField(
            model_name="message",
            name="price",
        ),
        migrations.RemoveField(
            model_name="room",
            name="price",
        ),
        migrations.AddField(
            model_name="message",
            name="body",
            field=models.TextField(default=""),
        ),
    ]
