# Generated by Django 4.1.7 on 2023-03-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wydarzenia", "0010_alter_message_options_remove_message_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.RemoveField(
            model_name="message",
            name="body",
        ),
        migrations.RemoveField(
            model_name="message",
            name="date",
        ),
        migrations.AddField(
            model_name="message",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
