# Generated by Django 4.1.7 on 2023-03-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wydarzenia", "0011_alter_message_options_remove_message_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="body",
            field=models.TextField(default=""),
        ),
    ]
