# Generated by Django 4.1.7 on 2023-03-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wydarzenia", "0012_message_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="price",
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
