# Generated by Django 4.1.7 on 2023-03-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wydarzenia", "0013_remove_message_price_alter_room_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
