# Generated by Django 4.1.6 on 2023-03-24 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wydarzenia", "0010_alter_topic_slug"),
        ("wydarzenia", "0014_alter_room_description"),
    ]

    operations = []
