# Generated by Django 4.1.6 on 2023-03-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wydarzenia", "0015_merge_20230324_1256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.SlugField(default="", max_length=200),
        ),
    ]
