# Generated by Django 4.1.7 on 2023-03-28 10:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("wydarzenia", "0016_alter_room_name_alter_topic_name_alter_topic_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="description",
            field=tinymce.models.HTMLField(blank=True, default=""),
        ),
    ]
