# Generated by Django 4.1.7 on 2023-03-24 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wydarzenia", "0015_room_image"),
        ("wydarzenia", "0016_alter_room_name_alter_topic_name_alter_topic_slug"),
    ]

    operations = []
