# Generated by Django 4.1.7 on 2023-03-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wydarzenia", "0017_alter_room_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
