# Generated by Django 4.1.7 on 2023-03-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wydarzenia", "0019_remove_room_time_alter_room_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
