# Generated by Django 4.1.7 on 2023-03-30 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wydarzenia", "0017_merge_20230324_1531"),
        ("wydarzenia", "0020_room_time_alter_room_date"),
    ]

    operations = []
