# Generated by Django 4.1.7 on 2023-03-30 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wydarzenia", "0021_merge_20230330_1142"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="image",
        ),
    ]
