# Generated by Django 4.1.7 on 2023-03-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wydarzenia", "0023_room_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
